interface Sounds {
  url: string;
  name: string;
  color: "W" | "B";
  keyCode: string;
}
export const pianoSounds: Sounds[] = [
  {
    url: "/audio/piano/piano48.wav",
    name: "도",
    color: "W",
    keyCode: "1",
  },
  {
    url: "/audio/piano/piano49.wav",
    name: "도#",
    color: "B",
    keyCode: "2",
  },
  {
    url: "/audio/piano/piano50.wav",
    name: "레",
    color: "W",
    keyCode: "3",
  },
  {
    url: "/audio/piano/piano51.wav",
    name: "레#",
    color: "B",
    keyCode: "4",
  },
  {
    url: "/audio/piano/piano52.wav",
    name: "미",
    color: "W",
    keyCode: "5",
  },
  {
    url: "/audio/piano/piano53.wav",
    name: "파",
    color: "W",
    keyCode: "6",
  },
  {
    url: "/audio/piano/piano54.wav",
    name: "파#",
    color: "B",
    keyCode: "7",
  },
  {
    url: "/audio/piano/piano55.wav",
    name: "솔",
    color: "W",
    keyCode: "8",
  },
  {
    url: "/audio/piano/piano56.wav",
    name: "솔#",
    color: "B",
    keyCode: "9",
  },
  {
    url: "/audio/piano/piano57.wav",
    name: "라",
    color: "W",
    keyCode: "0",
  },
  {
    url: "/audio/piano/piano58.wav",
    name: "라#",
    color: "B",
    keyCode: "-",
  },
  {
    url: "/audio/piano/piano59.wav",
    name: "시",
    color: "W",
    keyCode: "=",
  },
  {
    url: "/audio/piano/piano60.wav",
    name: "도",
    color: "W",
    keyCode: "q",
  },
  {
    url: "/audio/piano/piano61.wav",
    name: "도#",
    color: "B",
    keyCode: "w",
  },
  {
    url: "/audio/piano/piano62.wav",
    name: "레",
    color: "W",
    keyCode: "e",
  },
  {
    url: "/audio/piano/piano63.wav",
    name: "레#",
    color: "B",
    keyCode: "r",
  },
  {
    url: "/audio/piano/piano64.wav",
    name: "미",
    color: "W",
    keyCode: "t",
  },
  {
    url: "/audio/piano/piano65.wav",
    name: "파",
    color: "W",
    keyCode: "y",
  },
  {
    url: "/audio/piano/piano66.wav",
    name: "파#",
    color: "B",
    keyCode: "u",
  },
  {
    url: "/audio/piano/piano67.wav",
    name: "솔",
    color: "W",
    keyCode: "i",
  },
  {
    url: "/audio/piano/piano68.wav",
    name: "솔#",
    color: "B",
    keyCode: "o",
  },
  {
    url: "/audio/piano/piano69.wav",
    name: "라",
    color: "W",
    keyCode: "p",
  },
  {
    url: "/audio/piano/piano70.wav",
    name: "라#",
    color: "B",
    keyCode: "[",
  },
  {
    url: "/audio/piano/piano71.wav",
    name: "시",
    color: "W",
    keyCode: "]",
  },
  {
    url: "/audio/piano/piano72.wav",
    name: "도",
    color: "W",
    keyCode: "a",
  },
  {
    url: "/audio/piano/piano73.wav",
    name: "도#",
    color: "B",
    keyCode: "s",
  },
  {
    url: "/audio/piano/piano74.wav",
    name: "레",
    color: "W",
    keyCode: "d",
  },
  {
    url: "/audio/piano/piano75.wav",
    name: "레#",
    color: "B",
    keyCode: "f",
  },
  {
    url: "/audio/piano/piano76.wav",
    name: "미",
    color: "W",
    keyCode: "g",
  },
  {
    url: "/audio/piano/piano77.wav",
    name: "파",
    color: "W",
    keyCode: "h",
  },
  {
    url: "/audio/piano/piano78.wav",
    name: "파#",
    color: "B",
    keyCode: "j",
  },
  {
    url: "/audio/piano/piano79.wav",
    name: "솔",
    color: "W",
    keyCode: "k",
  },
  {
    url: "/audio/piano/piano80.wav",
    name: "솔#",
    color: "B",
    keyCode: "l",
  },
  {
    url: "/audio/piano/piano81.wav",
    name: "라",
    color: "W",
    keyCode: ";",
  },
  {
    url: "/audio/piano/piano82.wav",
    name: "라#",
    color: "B",
    keyCode: "'",
  },
  {
    url: "/audio/piano/piano83.wav",
    name: "시",
    color: "W",
    keyCode: "Enter",
  },
];

export const drumSounds: Sounds[] = [
  {
    url: "/audio/drum/FX1.wav",
    name: "FX1",
    color: "W",
    keyCode: "1",
  },
  {
    url: "/audio/drum/FX2.wav",
    name: "FX2",
    color: "W",
    keyCode: "2",
  },
  {
    url: "/audio/drum/FX3.wav",
    name: "FX3",
    color: "W",
    keyCode: "3",
  },
  {
    url: "/audio/drum/FX4.wav",
    name: "FX4",
    color: "W",
    keyCode: "4",
  },
  {
    url: "/audio/drum/FX5.wav",
    name: "FX5",
    color: "W",
    keyCode: "5",
  },
  {
    url: "/audio/drum/FX6.wav",
    name: "FX6",
    color: "W",
    keyCode: "6",
  },
  {
    url: "/audio/drum/FX7.wav",
    name: "FX7",
    color: "W",
    keyCode: "7",
  },
  {
    url: "/audio/drum/FX8.wav",
    name: "FX8",
    color: "W",
    keyCode: "8",
  },
  {
    url: "/audio/drum/Glitch1.wav",
    name: "Glitch1",
    color: "W",
    keyCode: "9",
  },
  {
    url: "/audio/drum/Glitch2.wav",
    name: "Glitch2",
    color: "W",
    keyCode: "0",
  },
  {
    url: "/audio/drum/Glitch3.wav",
    name: "Glitch3",
    color: "W",
    keyCode: "-",
  },
  {
    url: "/audio/drum/Glitch4.wav",
    name: "Glitch4",
    color: "W",
    keyCode: "=",
  },
  {
    url: "/audio/drum/Pad1.wav",
    name: "Pad1",
    color: "W",
    keyCode: "q",
  },
  {
    url: "/audio/drum/Pad2.wav",
    name: "Pad2",
    color: "W",
    keyCode: "w",
  },
  {
    url: "/audio/drum/Pad3.wav",
    name: "Pad3",
    color: "W",
    keyCode: "e",
  },
  {
    url: "/audio/drum/Pad4.wav",
    name: "Pad4",
    color: "W",
    keyCode: "r",
  },
  {
    url: "/audio/drum/Pad5.wav",
    name: "Pad5",
    color: "W",
    keyCode: "t",
  },
  {
    url: "/audio/drum/Pad6.wav",
    name: "Pad6",
    color: "W",
    keyCode: "y",
  },
  {
    url: "/audio/drum/Pad7.wav",
    name: "Pad7",
    color: "W",
    keyCode: "u",
  },
  {
    url: "/audio/drum/Pad8.wav",
    name: "Pad8",
    color: "W",
    keyCode: "i",
  },
  {
    url: "/audio/drum/Pad9.wav",
    name: "Pad9",
    color: "W",
    keyCode: "o",
  },
  {
    url: "/audio/drum/Pad10.wav",
    name: "pad10",
    color: "W",
    keyCode: "p",
  },
  {
    url: "/audio/drum/Pad11.wav",
    name: "Pad11",
    color: "W",
    keyCode: "[",
  },
  {
    url: "/audio/drum/Pad12.wav",
    name: "Pad12",
    color: "W",
    keyCode: "]",
  },
  {
    url: "/audio/drum/Pad13.wav",
    name: "Pad13",
    color: "W",
    keyCode: "a",
  },

  {
    url: "/audio/drum/Pad15.wav",
    name: "Pad15",
    color: "W",
    keyCode: "s",
  },

  {
    url: "/audio/drum/Pad16.wav",
    name: "Pad16",
    color: "W",
    keyCode: "d",
  },
  {
    url: "/audio/drum/Kick1.wav",
    name: "kick1",
    color: "W",
    keyCode: "f",
  },
  {
    url: "/audio/drum/Kick2.wav",
    name: "Kick2",
    color: "W",
    keyCode: "g",
  },

  {
    url: "/audio/drum/Hat1.wav",
    name: "Hat1",
    color: "W",
    keyCode: "h",
  },
  {
    url: "/audio/drum/Hat2.wav",
    name: "Hat2",
    color: "W",
    keyCode: "j",
  },
  {
    url: "/audio/drum/Hat3.wav",
    name: "Hat3",
    color: "W",
    keyCode: "k",
  },
  {
    url: "/audio/drum/Snare1.wav",
    name: "Snare1",
    color: "W",
    keyCode: "l",
  },
  {
    url: "/audio/drum/Snare2.wav",
    name: "Snare2",
    color: "W",
    keyCode: ";",
  },
  {
    url: "/audio/drum/Snare3.wav",
    name: "Snare3",
    color: "W",
    keyCode: "'",
  },
  {
    url: "/audio/drum/Snare4.wav",
    name: "Snare4",
    color: "W",
    keyCode: "Enter",
  },
];
